steps:
- name: 'gcr.io/cloud-builders/gcloud'
  script: |
    gcloud run deploy cloudrunservice --image us-docker.pkg.dev/cloudrun/container/chatgpt-tetris --region asia-northeast1 --platform managed --allow-unauthenticated
